### ISSUE TITLE
syntax error - ares_query_soa_result' has no len()

### ISSUE THREAD

**Issue by luton1507** [WeebSec/weebdns#2]
Traceback (most recent call last):
  File "weebdns.py", line 197, in <module>
    default_loop()
  File "weebdns.py", line 174, in default_loop
    run = loop.run_until_complete(aiodns_query(resolver))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "weebdns.py", line 97, in aiodns_query
    await aiodns_request(target, query_type, resolver)
  File "weebdns.py", line 66, in aiodns_request
    if len(results) == 0:
TypeError: object of type 'ares_query_soa_result' has no len()

**Comment by imdantesco** [comment]
I have the same problem, Did you manage to solve?

**Comment by D3m0ni4k** [comment]
Use it on root os

**Comment by Luciferr0666** [comment]
already running on root still having the same issue
